### ISSUE TITLE
[BUG] Apklis_http_web_api devuelve un ApklisErrorModel con mensaje: "type 'Null' is not a subtype of type String in type cast"

### ISSUE THREAD

**Issue by alaincj** [fluttercuba/apklis-dart-flutter#16]
**Descripción del error:**
Cuando hago una petición a la api de Apklis_http_web_api con el método api.get(["package_name"]) donde package_name es el nombre del paquete de mi aplicación me devuelve un ApklisErrorModel con el mensaje: "type 'Null' is not a subtype of type String in type cast".

**Reproducción del error:**
Pasos para reproducir el comportamiento:

1. Cree una página nueva (StatefulWidget)
2. En el initState llame al método de chequear la versión de la app en Apklis usando la api (como se muestra en la captura 1), puede obtener el package_name de forma manual escribiendolo directamente o usar el paquete "package_info_plus". Mi paquete es: "works.a4t0mic.recetario"
3. Abrir la consola de depuración para ver mensaje de error o pestaña de depuración para ver el modelo devuelto y el error

**Comportamiento esperado**
Debería devolver un SuccessApklisApiResult con result = "ApklisModel" y a partir de ahí hacer las comparaciones.

**Capturas de pantalla**
Código utilizado:
![code](https://user-images.githubusercontent.com/82970898/139970767-633e7597-9cd3-42a9-b393-1e509068a98b.png)
Error devuelto:
![Captura de pantalla (100)](https://user-images.githubusercontent.com/82970898/139970790-59667a94-7937-4aeb-84b2-74a5c125585f.png)

**Escritorio:**

  - SO: [Windows 10 ver. 2004 (Windows_NT x64 10.0.19041)]
  - IDE [VSCode Versión: 1.61.2]
  - Fecha: 2021-10-19T14:57:20.575Z
  - Electron: 13.5.1
  - Chrome: 91.0.4472.164
  - Node.js: 14.16.0

**Smartphone:**

  - Dispositivo: [Alcatel TCL 5024A]
  - SO: [Android 9]

**Flutter Doctor:**
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [VersiÃ³n 10.0.19041.207], locale es-ES)
    • Flutter version 2.5.0 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\4t0m\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (2 available)
    • 5024A (mobile) • 5HLA01CNEOD03AU • android-arm64  • Android 9 (API 28)
    • Chrome (web)   • chrome          • web-javascript • Google Chrome 87.0.4280.88

**Comment by leynier** [comment]
Muchas gracias por reportar el problema, ya debe estar solucionado con el cambio del siguiente commit https://github.com/fluttercuba/apklis-dart-flutter/commit/e2ea0e0a6aee0e8b042131536e51279e57c2213a

**Comment by leynier** [comment]
@all-contributors please add @alaincj for bug

**Comment by alaincj** [comment]
> Muchas gracias por reportar el problema, ya debe estar solucionado con el cambio del siguiente commit [e2ea0e0](https://github.com/fluttercuba/apklis-dart-flutter/commit/e2ea0e0a6aee0e8b042131536e51279e57c2213a)

Gracias a uds. por el desarrollo del paquete y a ti por el fix tan inmediato!
